FROM python:3.11-alpine

RUN apk add --no-cache \
    gcc \
    musl-dev \
    linux-headers \
    ffmpeg \
    libffi-dev \
    openssl-dev \
    ca-certificates

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY app.py .

RUN adduser -D appuser
# USER appuser

EXPOSE 5000

CMD ["python", "app.py"]
